source ~/.local/share/omakub/defaults/zsh/rc

# Source plugins
autoload -U compinit; compinit
source $ZSH_PLUGINS_DIR/fzf-tab/fzf-tab.plugin.zsh
source $ZSH_PLUGINS_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSH_PLUGINS_DIR/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
fpath=($ZSH_PLUGINS_DIR/zsh-completions/src $fpath)

# Editor used by CLI
export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"
